### ISSUE TITLE
Mentor discussion text editor: ordered list eats one letter

### ISSUE THREAD

**Issue by b10s** [exercism/website-copy#1528] opened 2020-04-03 03:16 UTC
![Selection_722](https://user-images.githubusercontent.com/4618288/78320667-ef69dc00-75a4-11ea-930d-ba6be3624981.png)
press Enter
![Selection_723](https://user-images.githubusercontent.com/4618288/78320680-f7c21700-75a4-11ea-86fe-a6c02096bdac.png)

**Comment by corneliusroemer** [comment] 2020-12-13 15:22
@ihid Misclassified issue: Belongs to main repo https://github.com/exercism/exercism

**Comment by angelikatyborska** [comment] 2021-11-23 18:06
The issue is about v2 which doesn't exist anymore. I double-checked and this doesn't happen in v3 in mentoring comments. I'll close this.

**Closed by angelikatyborska** 2021-11-23 18:06 UTC

**Comment by iHiD** [comment] 2021-11-24 11:32
Thanks Angelika!
