### ISSUE TITLE
JavaScript Meetup Mentoring Notes Broken Link

### ISSUE THREAD

**Issue by pertrai1** [exercism/website-copy#2057] opened 2021-09-04 14:06 UTC
The link here is broken when I follow to GitHub:

```
This exercise doesn't have any mentoring notes yet. Mentoring notes
are written by our community. Please help get them started for this
exercise by sending a Pull Request on GitHub.
```

![mentor-notes-pull-request-bad-link](https://user-images.githubusercontent.com/442374/132097215-f39b8113-ece7-411b-b375-00aefc9e2674.jpg)

**Comment by angelikatyborska** [comment] 2021-09-05 10:33
This is a duplicate of https://github.com/exercism/exercism/issues/5769

I will close this issue but please observe the other one for updates! This is definitely a bug.

**Closed by angelikatyborska** 2021-09-05 10:33 UTC
