### ISSUE TITLE
Broken Link  in python exercises

### ISSUE THREAD

**Issue by infamousdegen** [exercism/website-copy#2052] opened 2021-09-02 07:25 UTC
![Screenshot from 2021-09-02 12-54-15](https://user-images.githubusercontent.com/83490717/131800790-378add34-a133-41db-b678-601b0a670266.png)

When we click the start in editor in all python exercises it redirects to a broken link

**Comment by angelikatyborska** [comment] 2021-09-02 07:49
Are you using "open in a new tab"? If yes, this issue is a duplicate of https://github.com/exercism/exercism/issues/5647

**Comment by infamousdegen** [comment] 2021-09-02 08:47
Yeah, I am sorry didn't see that before

**Closed** 2021-09-02 08:47 UTC
